import uuid

BOOKS = [
    {"id": str(uuid.uuid4()), "title": "Clean Code", "author": "Robert C. Martin"},
    {"id": str(uuid.uuid4()), "title": "The Pragmatic Programmer", "author": "Andrew Hunt"},
    {"id": str(uuid.uuid4()), "title": "FastAPI Essentials", "author": "Lê Tuấn Bình"},
    {"id": str(uuid.uuid4()), "title": "Python Tricks", "author": "Dan Bader"},
    {"id": str(uuid.uuid4()), "title": "Effective Python", "author": "Brett Slatkin"},
    {"id": str(uuid.uuid4()), "title": "Introduction to Algorithms", "author": "Thomas H. Cormen"},
    {"id": str(uuid.uuid4()), "title": "Design Patterns", "author": "Erich Gamma"},
    {"id": str(uuid.uuid4()), "title": "Refactoring", "author": "Martin Fowler"},
    {"id": str(uuid.uuid4()), "title": "You Don’t Know JS", "author": "Kyle Simpson"},
    {"id": str(uuid.uuid4()), "title": "Eloquent JavaScript", "author": "Marijn Haverbeke"},
    {"id": str(uuid.uuid4()), "title": "Learning Python", "author": "Mark Lutz"},
    {"id": str(uuid.uuid4()), "title": "Fluent Python", "author": "Luciano Ramalho"},
    {"id": str(uuid.uuid4()), "title": "Python Cookbook", "author": "David Beazley"},
    {"id": str(uuid.uuid4()), "title": "Automate the Boring Stuff", "author": "Al Sweigart"},
    {"id": str(uuid.uuid4()), "title": "Head First Design Patterns", "author": "Eric Freeman"},
    {"id": str(uuid.uuid4()), "title": "Cracking the Coding Interview", "author": "Gayle Laakmann McDowell"},
    {"id": str(uuid.uuid4()), "title": "Deep Learning", "author": "Ian Goodfellow"},
    {"id": str(uuid.uuid4()), "title": "Hands-On Machine Learning", "author": "Aurélien Géron"},
    {"id": str(uuid.uuid4()), "title": "Artificial Intelligence: A Modern Approach", "author": "Stuart Russell"},
    {"id": str(uuid.uuid4()), "title": "Clean Architecture", "author": "Robert C. Martin"},
    {"id": str(uuid.uuid4()), "title": "Domain-Driven Design", "author": "Eric Evans"},
    {"id": str(uuid.uuid4()), "title": "The Clean Coder", "author": "Robert C. Martin"},
    {"id": str(uuid.uuid4()), "title": "Code Complete", "author": "Steve McConnell"},
    {"id": str(uuid.uuid4()), "title": "Working Effectively with Legacy Code", "author": "Michael Feathers"},
    {"id": str(uuid.uuid4()), "title": "Programming Pearls", "author": "Jon Bentley"},
    {"id": str(uuid.uuid4()), "title": "Python for Data Analysis", "author": "Wes McKinney"},
    {"id": str(uuid.uuid4()), "title": "Data Science from Scratch", "author": "Joel Grus"},
    {"id": str(uuid.uuid4()), "title": "Think Python", "author": "Allen B. Downey"},
    {"id": str(uuid.uuid4()), "title": "Python Programming: An Introduction to Computer Science", "author": "John Zelle"},
    {"id": str(uuid.uuid4()), "title": "Effective Java", "author": "Joshua Bloch"},
    {"id": str(uuid.uuid4()), "title": "Java Concurrency in Practice", "author": "Brian Goetz"},
    {"id": str(uuid.uuid4()), "title": "Spring in Action", "author": "Craig Walls"},
    {"id": str(uuid.uuid4()), "title": "Microservices Patterns", "author": "Chris Richardson"},
    {"id": str(uuid.uuid4()), "title": "Building Microservices", "author": "Sam Newman"},
    {"id": str(uuid.uuid4()), "title": "Kubernetes Up & Running", "author": "Kelsey Hightower"},
    {"id": str(uuid.uuid4()), "title": "Docker Deep Dive", "author": "Nigel Poulton"},
    {"id": str(uuid.uuid4()), "title": "Python Crash Course", "author": "Eric Matthes"},
    {"id": str(uuid.uuid4()), "title": "Learning React", "author": "Alex Banks"},
    {"id": str(uuid.uuid4()), "title": "React Up & Running", "author": "Stoyan Stefanov"},
    {"id": str(uuid.uuid4()), "title": "JavaScript: The Good Parts", "author": "Douglas Crockford"},
    {"id": str(uuid.uuid4()), "title": "Effective TypeScript", "author": "Dan Vanderkam"},
    {"id": str(uuid.uuid4()), "title": "Programming TypeScript", "author": "Boris Cherny"},
    {"id": str(uuid.uuid4()), "title": "The Art of Computer Programming", "author": "Donald Knuth"},
    {"id": str(uuid.uuid4()), "title": "Introduction to the Theory of Computation", "author": "Michael Sipser"},
    {"id": str(uuid.uuid4()), "title": "Structure and Interpretation of Computer Programs", "author": "Harold Abelson"},
    {"id": str(uuid.uuid4()), "title": "Code: The Hidden Language of Computer Hardware and Software", "author": "Charles Petzold"},
    {"id": str(uuid.uuid4()), "title": "Computer Networking: A Top-Down Approach", "author": "James Kurose"},
    {"id": str(uuid.uuid4()), "title": "The C Programming Language", "author": "Brian Kernighan"},
    {"id": str(uuid.uuid4()), "title": "Algorithms", "author": "Robert Sedgewick"},
    {"id": str(uuid.uuid4()), "title": "Introduction to Machine Learning with Python", "author": "Andreas C. Müller"},
]
